version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-keycloak
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      [
        "start-dev",
        "--db=postgres",
        "--db-url-host=postgres",
        "--db-username=${POSTGRES_USER}",
        "--db-password=${POSTGRES_PASSWORD}",
        "--db-url-database=${POSTGRES_DB}",
        "--hostname=localhost"
      ]

volumes:
  postgres_data:
