eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_URL}
  instance:
    hostname: ${GATEWAY_HOST_NAME}
    instance-id: ${spring.application.name}:${random.uuid}

management:
  tracing.sampling.probability: 1

server:
  port: 8765

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/v1/product-service/**
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/v1/order-service/**
      routes[2]:
        id: shopping-cart-service
        uri: lb://shopping-cart-service
        predicates[0]: Path=/api/v1/shopping-cart-service/**
      routes[3]:
        id: payment-service
        uri: lb://payment-service
        predicates[0]: Path=/api/v1/payment-service/**
      routes[4]:
        id: notification-service
        uri: lb://notification-service
        predicates[0]: Path=/api/v1/notification-service/**

      # Routes for metrics
      routes[5]:
        id: product-service-metrics
        uri: lb://product-service
        predicates:
          - Path=/metrics/product-service
        filters:
          - RewritePath=/metrics/product-service, /actuator/prometheus
          - PreserveHostHeader
          - RemoveRequestHeader=Cookie
      routes[6]:
        id: order-service-metrics
        uri: lb://order-service
        predicates:
          - Path=/metrics/order-service
        filters:
          - RewritePath=/metrics/order-service, /actuator/prometheus
          - PreserveHostHeader
          - RemoveRequestHeader=Cookie
      routes[7]:
        id: shopping-cart-service-metrics
        uri: lb://shopping-cart-service
        predicates:
          - Path=/metrics/shopping-cart-service
        filters:
          - RewritePath=/metrics/shopping-cart-service, /actuator/prometheus
          - PreserveHostHeader
          - RemoveRequestHeader=Cookie
      routes[8]:
        id: payment-service-metrics
        uri: lb://payment-service
        predicates:
          - Path=/metrics/payment-service
        filters:
          - RewritePath=/metrics/payment-service, /actuator/prometheus
          - PreserveHostHeader
          - RemoveRequestHeader=Cookie
      routes[9]:
        id: notification-service-metrics
        uri: lb://notification-service
        predicates:
          - Path=/metrics/notification-service
        filters:
          - RewritePath=/metrics/notification-service, /actuator/prometheus
          - PreserveHostHeader
          - RemoveRequestHeader=Cookie


