spring:
  datasource:
    url: ${POSTGRES_PAYMENT_SERVICE_DB_URL}
    username:  ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  # RabbitMQ config
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

paystack:
  secret: ${PAYSTACK_SECRET}
  verify:
    url: ${PAYSTACK_VERIFICATION_URL}