global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'auth-server'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'user'
      password: 'password'
    static_configs:
      - targets: ['host.docker.internal:8080']
#      - targets: ['auth-server:8080']
        labels:
          application: "Authorization Server"

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'user'
      password: 'password'
    static_configs:
      - targets: ['host.docker.internal:8765']
#      - targets: ['gateway:8765']
        labels:
          application: "Gateway Server"

  - job_name: 'product-service'
    metrics_path: '/metrics/product-service'
    basic_auth:
      username: 'user'
      password: 'password'
    static_configs:
      - targets: ['host.docker.internal:8765']
#      - targets: ['gateway:8765']
        labels:
          application: "Product Service"

  - job_name: 'order-service'
    metrics_path: '/metrics/order-service'
    basic_auth:
      username: 'user'
      password: 'password'
    static_configs:
      - targets: ['host.docker.internal:8765']
#      - targets: ['gateway:8765']
        labels:
          application: "Order Service"

